/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Cobranca } from "./Cobranca";
import { CobrancaCountArgs } from "./CobrancaCountArgs";
import { CobrancaFindManyArgs } from "./CobrancaFindManyArgs";
import { CobrancaFindUniqueArgs } from "./CobrancaFindUniqueArgs";
import { DeleteCobrancaArgs } from "./DeleteCobrancaArgs";
import { CobrancaService } from "../cobranca.service";
@graphql.Resolver(() => Cobranca)
export class CobrancaResolverBase {
  constructor(protected readonly service: CobrancaService) {}

  async _cobrancasMeta(
    @graphql.Args() args: CobrancaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Cobranca])
  async cobrancas(
    @graphql.Args() args: CobrancaFindManyArgs
  ): Promise<Cobranca[]> {
    return this.service.cobrancas(args);
  }

  @graphql.Query(() => Cobranca, { nullable: true })
  async cobranca(
    @graphql.Args() args: CobrancaFindUniqueArgs
  ): Promise<Cobranca | null> {
    const result = await this.service.cobranca(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Cobranca)
  async deleteCobranca(
    @graphql.Args() args: DeleteCobrancaArgs
  ): Promise<Cobranca | null> {
    try {
      return await this.service.deleteCobranca(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
