/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Parcela } from "./Parcela";
import { ParcelaCountArgs } from "./ParcelaCountArgs";
import { ParcelaFindManyArgs } from "./ParcelaFindManyArgs";
import { ParcelaFindUniqueArgs } from "./ParcelaFindUniqueArgs";
import { DeleteParcelaArgs } from "./DeleteParcelaArgs";
import { ParcelaService } from "../parcela.service";
@graphql.Resolver(() => Parcela)
export class ParcelaResolverBase {
  constructor(protected readonly service: ParcelaService) {}

  async _parcelasMeta(
    @graphql.Args() args: ParcelaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Parcela])
  async parcelas(
    @graphql.Args() args: ParcelaFindManyArgs
  ): Promise<Parcela[]> {
    return this.service.parcelas(args);
  }

  @graphql.Query(() => Parcela, { nullable: true })
  async parcela(
    @graphql.Args() args: ParcelaFindUniqueArgs
  ): Promise<Parcela | null> {
    const result = await this.service.parcela(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Parcela)
  async deleteParcela(
    @graphql.Args() args: DeleteParcelaArgs
  ): Promise<Parcela | null> {
    try {
      return await this.service.deleteParcela(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
