/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Classificacao } from "./Classificacao";
import { ClassificacaoCountArgs } from "./ClassificacaoCountArgs";
import { ClassificacaoFindManyArgs } from "./ClassificacaoFindManyArgs";
import { ClassificacaoFindUniqueArgs } from "./ClassificacaoFindUniqueArgs";
import { DeleteClassificacaoArgs } from "./DeleteClassificacaoArgs";
import { ClassificacaoService } from "../classificacao.service";
@graphql.Resolver(() => Classificacao)
export class ClassificacaoResolverBase {
  constructor(protected readonly service: ClassificacaoService) {}

  async _classificacaosMeta(
    @graphql.Args() args: ClassificacaoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Classificacao])
  async classificacaos(
    @graphql.Args() args: ClassificacaoFindManyArgs
  ): Promise<Classificacao[]> {
    return this.service.classificacaos(args);
  }

  @graphql.Query(() => Classificacao, { nullable: true })
  async classificacao(
    @graphql.Args() args: ClassificacaoFindUniqueArgs
  ): Promise<Classificacao | null> {
    const result = await this.service.classificacao(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Classificacao)
  async deleteClassificacao(
    @graphql.Args() args: DeleteClassificacaoArgs
  ): Promise<Classificacao | null> {
    try {
      return await this.service.deleteClassificacao(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
